### ISSUE TITLE
Doesn't seem to work with GHE

### ISSUE THREAD

**Issue by retr0h** [caarlos0/org-stats#26] opened 2020-03-16 23:04 UTC
org-stats --token  xxx --org engx --github-url https://ghe.private/

GET https://ghe.private/login?return_to=https%3A%2F%2Fghe.private%2Forgs%2Fengx%2Frepos%3Fper_page%3D10: 406  []

Issue seems to be /orgs/$org/repos doesn't exist.

**Comment by caarlos0** [comment] 2021-07-13 01:08
just noticed in the error: you need to pass the API url of your github enterprise, not the UI URL

so this is likely not a bug... closing

**Closed by caarlos0** 2021-07-13 01:08 UTC
